repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: rnasequencing
  description: RNA sequencing pipeline
  author: Mykyta Borodin, Eisenmann Bastian
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
