contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnasequencing channel"
    url: https://nfcore.slack.com/channels/rnasequencing
    about: Discussion about the nf-core/rnasequencing pipeline
